name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: init bit.dev
        run: |
          echo "Adding bit.dev to npm registry"
          npm config set @bit:registry https://node.bit.dev
          npm config set //node.bit.dev/:_authToken ${BIT_TOKEN}
          echo "Completed adding bit.dev to npm registry"
        env:
          BIT_TOKEN: ${{ secrets.BIT_TOKEN }}
      - run: npm install
      - run: npm run build
        env:
          APP_SENTRY_KEY: ${{ secrets.APP_SENTRY_KEY }}
          APP_BACKEND_CLIENT_ID: ${{ secrets.APP_BACKEND_CLIENT_ID }}
          APP_MAPBOX_MAP_KEY: ${{ secrets.APP_MAPBOX_MAP_KEY }}
      - run: npm run test
      - run: npm run test:eslint
        env:
          APP_SENTRY_KEY: ${{ secrets.APP_SENTRY_KEY }}
          APP_MAPBOX_MAP_KEY: ${{ secrets.APP_MAPBOX_MAP_KEY }}
          APP_BACKEND_CLIENT_ID: ${{ secrets.APP_BACKEND_CLIENT_ID }}

      - uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          scope: ${{ secrets.VERCEL_TEAM_ID }}
          vercel-args: '--prod'
      
      - run: npm run test:acceptance
        env:
          PLANT_NET_API_KEY: ${{ secrets.PLANT_NET_API_KEY }}