name: Sanity Check

on:
  schedule:
    - cron: '0 4 * * *'

jobs:
  acceptance-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: init bit.dev
        run: |
          echo "Adding bit.dev to npm registry"
          npm config set @bit:registry https://node.bit.dev
          npm config set //node.bit.dev/:_authToken ${BIT_TOKEN}
          echo "Completed adding bit.dev to npm registry"
        env:
          BIT_TOKEN: ${{ secrets.BIT_TOKEN }}
      - run: npm install
      - run: npm run test:acceptance
        env:
          PLANT_NET_API_KEY: ${{ secrets.PLANT_NET_API_KEY }}